#!/usr/bin/env node

const fs = require("fs");
const path = require("path");
const validStatuses = new Set(["pending", "in_progress", "completed", "blocked"]);
const root = path.join(process.cwd(), ".tmp", "tasks");

function fail(message) { console.error(`Error: ${message}`); process.exit(1); }
function isDirectory(target) { try { return fs.statSync(target).isDirectory(); } catch { return false; } }
function readJson(target) { try { return JSON.parse(fs.readFileSync(target, "utf8")); } catch (error) { fail(`cannot read valid JSON from ${target}: ${error.message}`); } }
function writeJson(target, value) { fs.writeFileSync(target, `${JSON.stringify(value, null, 2)}\n`, "utf8"); }
function taskFile(feature) { return path.join(root, feature, "task.json"); }
function features(feature) { if (feature) { if (!isDirectory(path.join(root, feature))) fail(`feature "${feature}" not found in ${root}`); return [feature]; } if (!isDirectory(root)) return []; return fs.readdirSync(root, { withFileTypes: true }).filter((entry) => entry.isDirectory() && entry.name !== "completed").map((entry) => entry.name).sort(); }
function subtasks(feature) { const directory = path.dirname(taskFile(feature)); return fs.readdirSync(directory).filter((name) => /^subtask_\d+\.json$/.test(name)).sort().map((name) => readJson(path.join(directory, name))).sort((left, right) => String(left.seq).localeCompare(String(right.seq))); }
function ready(task, all) { if (task.status !== "pending") return false; const completed = new Set(all.filter((item) => item.status === "completed").map((item) => String(item.seq))); return (Array.isArray(task.depends_on) ? task.depends_on : []).every((dependency) => completed.has(String(dependency))); }
function counts(items) { return items.reduce((result, item) => { const state = String(item.status || "pending"); result[state] = (result[state] || 0) + 1; return result; }, {}); }
function status(feature) { const names = features(feature); if (!names.length) return console.log("No active tasks found."); for (const name of names) { const task = readJson(taskFile(name)); const items = subtasks(name); const summary = counts(items); const completed = summary.completed || 0; console.log(`[${name}] ${task.name || name}`); console.log(`  Status: ${task.status || "active"} | Progress: ${items.length ? Math.round(completed * 100 / items.length) : 0}% (${completed}/${items.length})`); console.log(`  Pending: ${summary.pending || 0} | In Progress: ${summary.in_progress || 0} | Completed: ${completed} | Blocked: ${summary.blocked || 0}`); } }
function candidates(feature, onlyParallel, asJson) { const result = []; for (const name of features(feature)) { const items = subtasks(name); for (const task of items) if (ready(task, items) && (!onlyParallel || task.parallel === true)) result.push({ feature: name, task_root: path.dirname(taskFile(name)), task_json_path: taskFile(name), subtask_path: path.join(path.dirname(taskFile(name)), `subtask_${String(task.seq).padStart(2, "0")}.json`), subtask: task }); } if (asJson) return console.log(JSON.stringify(result, null, 2)); console.log(onlyParallel ? "=== Parallel Ready Tasks ===" : "=== Ready Tasks (deps satisfied) ==="); if (!result.length) return console.log("None."); for (const item of result) console.log(`[${item.feature}] ${String(item.subtask.seq).padStart(2, "0")} - ${item.subtask.title || "Untitled"} [${item.subtask.parallel === true ? "parallel" : "sequential"}]`); }
function blocked(feature) { let found = false; console.log("=== Blocked Tasks ==="); for (const name of features(feature)) { const items = subtasks(name); const completed = new Set(items.filter((item) => item.status === "completed").map((item) => String(item.seq))); for (const task of items) { const unmet = (Array.isArray(task.depends_on) ? task.depends_on : []).map(String).filter((dependency) => !completed.has(dependency)); if (task.status === "blocked" || (task.status === "pending" && unmet.length)) { found = true; console.log(`[${name}] ${task.seq} - ${task.title || "Untitled"}: ${task.status === "blocked" ? "explicitly blocked" : `waiting for ${unmet.join(", ")}`}`); } } } if (!found) console.log("None."); }
function deps(feature, sequence) { const items = subtasks(feature); const bySequence = new Map(items.map((task) => [String(task.seq), task])); function visit(seq, prefix, seen) { const task = bySequence.get(seq); if (!task) return console.log(`${prefix}${seq} - missing dependency`); console.log(`${prefix}${seq} - ${task.title || "Untitled"} [${task.status || "pending"}]`); if (seen.has(seq)) return; const nextSeen = new Set(seen); nextSeen.add(seq); for (const dependency of Array.isArray(task.depends_on) ? task.depends_on : []) visit(String(dependency), `${prefix}  `, nextSeen); } console.log(`=== Dependency Tree: ${feature}/${sequence} ===`); visit(sequence, "", new Set()); }
function complete(feature, sequence, summary) { if (!summary) fail("a completion summary is required"); if (summary.length > 200) fail("completion summary must be 200 characters or fewer"); const normalized = sequence.padStart(2, "0"); const file = path.join(root, feature, `subtask_${normalized}.json`); if (!fs.existsSync(file)) fail(`subtask ${feature}/${sequence} not found`); const task = readJson(file); const items = subtasks(feature); if (!ready(task, items) && task.status !== "completed") fail(`dependencies for ${feature}/${normalized} are not satisfied`); task.status = "completed"; task.completed_at = new Date().toISOString(); task.completion_summary = summary; writeJson(file, task); const featureTask = readJson(taskFile(feature)); const completed = subtasks(feature).filter((item) => item.status === "completed").length; featureTask.completed_count = completed; if (completed === items.length && items.length) { featureTask.status = "completed"; featureTask.completed_at = new Date().toISOString(); } writeJson(taskFile(feature), featureTask); console.log(`Marked ${feature}/${normalized} as completed.`); }
function validateFeature(feature) { const errors = []; const file = taskFile(feature); if (!fs.existsSync(file)) return ["task.json is missing"]; const task = readJson(file); const items = subtasks(feature); if (task.id !== feature) errors.push(`task id must equal "${feature}"`); if (task.subtask_count !== undefined && Number(task.subtask_count) !== items.length) errors.push(`subtask_count is ${task.subtask_count}, found ${items.length} files`); const ids = new Set(); const bySequence = new Map(); for (const item of items) { const seq = String(item.seq || ""); if (!/^\d{2}$/.test(seq)) errors.push(`invalid sequence "${seq}"`); if (ids.has(seq)) errors.push(`duplicate sequence "${seq}"`); ids.add(seq); bySequence.set(seq, item); if (item.id !== `${feature}-${seq}`) errors.push(`subtask ${seq} has invalid id`); if (!validStatuses.has(String(item.status))) errors.push(`subtask ${seq} has invalid status`); if (!Array.isArray(item.depends_on)) errors.push(`subtask ${seq} is missing depends_on`); if (!Array.isArray(item.acceptance_criteria) || !item.acceptance_criteria.length) errors.push(`subtask ${seq} needs acceptance_criteria`); if (!Array.isArray(item.deliverables) || !item.deliverables.length) errors.push(`subtask ${seq} needs deliverables`); } const visiting = new Set(); const visited = new Set(); function walk(seq) { if (visiting.has(seq)) { errors.push(`circular dependency involving ${seq}`); return; } if (visited.has(seq)) return; visiting.add(seq); const item = bySequence.get(seq); for (const dependency of Array.isArray(item.depends_on) ? item.depends_on.map(String) : []) { if (!bySequence.has(dependency)) errors.push(`subtask ${seq} depends on missing ${dependency}`); else if (dependency === seq) errors.push(`subtask ${seq} depends on itself`); else walk(dependency); } visiting.delete(seq); visited.add(seq); } for (const seq of bySequence.keys()) walk(seq); return [...new Set(errors)]; }
function validate(feature) { const names = features(feature); if (!names.length) return console.log("No active tasks found."); let failed = false; for (const name of names) { const errors = validateFeature(name); if (!errors.length) console.log(`[${name}] All checks passed.`); else { failed = true; console.log(`[${name}]\n  ${errors.join("\n  ")}`); } } if (failed) process.exitCode = 1; }
function help() { console.log("Usage: task-cli.ts <status|next|parallel|deps|blocked|complete|validate> [arguments]\n  next [--json] [feature]\n  parallel [--json] [feature]"); }
const [command, ...args] = process.argv.slice(2);
switch (command) { case "status": status(args[0]); break; case "next": candidates(args[0] === "--json" ? args[1] : args[0], false, args[0] === "--json"); break; case "parallel": candidates(args[0] === "--json" ? args[1] : args[0], true, args[0] === "--json"); break; case "blocked": blocked(args[0]); break; case "deps": if (!args[0] || !args[1]) fail("usage: deps <feature> <seq>"); deps(args[0], args[1]); break; case "complete": if (!args[0] || !args[1]) fail("usage: complete <feature> <seq> <summary>"); complete(args[0], args[1], args.slice(2).join(" ")); break; case "validate": validate(args[0]); break; case "help": case "-h": case "--help": case undefined: help(); break; default: fail(`unknown command "${command}"`); }
